### ISSUE TITLE
backoff - Requirements not found

### ISSUE THREAD

**Issue by IonutNeagu** [ofalvai/home-assistant-candy#198]
Logger: homeassistant.setup
Source: setup.py:184
First occurred: 09:57:27 (1 occurrences)
Last logged: 09:57:27

Home Assistant: 2022.11.0b0 

Setup failed for custom integration candy: Requirements for candy not found: ['backoff>=1.8.0,<2.0.0'].

**Comment by luisleonardo** [comment]
Same here :)

**Comment by Traxeronus** [comment]
Logger: homeassistant.setup
Source: setup.py:184
First occurred: 10:15:17 (1 occurrences)
Last logged: 10:15:17

Setup failed for custom integration candy: Requirements for candy not found: ['backoff>=1.8.0,<2.0.0'].

**Comment by IonutNeagu** [comment]
Modify this file **\custom_components\candy\manifest.json** , then pass to requirements ["backoff>=1.8.0,<**=**2.0.0"]

**Comment by Traxeronus** [comment]
Not fixed:

Logger: homeassistant.setup
Source: setup.py:168
First occurred: 13:30:32 (1 occurrences)
Last logged: 13:30:32

Setup failed for candy: Integration not found.

**Comment by Traxeronus** [comment]
Any help pls? Thx

**Comment by rogodra** [comment]
> Modify this file **\custom_components\candy\manifest.json** , then pass to requirements ["backoff>=1.8.0,<=2.0.0"]

Thanks, that solved the problem for me.

**Comment by maobuz** [comment]
well done i changed backoff>=1.8.0,<2.0.0 in backoff>=1.8.0,<=2.0.0 and now work

**Comment by antoweb** [comment]
In my case i have to modified like that:

manifest.json line 8 to
  "requirements": ["backoff>=1.8.0,<2.2.1"],

Because my version was greater than 2.0.0
now work

**Comment by ofalvai** [comment]
Hello everyone!

Apologies for not noticing this earlier, my GitHub notifications were messed up and I missed all the issue and PR activity in this repo.

I issued a hotfix as version 0.7.1, you can update the custom component in HACS.
