### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by alancoleman1972** [ofalvai/home-assistant-candy#2]
Hi Oliver

Thanks for creating this integration.

I seem to be struggling to get it to execute.  I have added the device IP and encryption key (detemined using CandySimplify-tool) but I get the following error on the integrations page in HA....

Retrying setup: Error communicating with API: 'FillR'

Any idea?
Thanks
Alan

**Comment by ofalvai** [comment]
@alancoleman1972 this is now fixed in the latest version, you can update via HACS
