### ISSUE TITLE
After last update HA integration not more working

### ISSUE THREAD

**Issue by antoweb** [ofalvai/home-assistant-candy#204]
Home Assistant 2022.11.0

Can you please fix this problem?

**Comment by akileos** [comment]
Same here, might be an easy fix, it's a python dependency issue. 
Here are additional infos for someone who might know why it was locked <2.0.0.

````
Logger: homeassistant.setup
Source: setup.py:184
First occurred: 17:53:33 (1 occurrences)
Last logged: 17:53:33

Setup failed for custom integration candy: Requirements for candy not found: ['backoff>=1.8.0,<2.0.0'].

````

```
me @ redacted ➜  ~  docker exec -it home-assistant bash
bash-5.1# python3
Python 3.10.7 (main, Sep 20 2022, 16:18:06) [GCC 11.2.1 20220219] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import backoff
>>> backoff.__version__
'2.2.1'
```

**Comment by antoweb** [comment]
ok modified manifest.json line 8 to
  "requirements": ["backoff>=1.8.0,<2.2.1"],

now work

**Comment by SoulOnFire** [comment]
> ok modified manifest.json line 8 to "requirements": ["backoff>=1.8.0,<2.2.1"],
> 
> now work

It's work for me!!

**Comment by dfsworld** [comment]
That worked for me too. Please mantainer, update this  :)

**Comment by Pacococo** [comment]
A mí también me funcionó, muchas gracias

**Comment by Apgeo77** [comment]
It started working perfectly again, I love you all

**Comment by mh166** [comment]
@ofalvai As the fix seems to work (thanks for that @antoweb), would you mind releasing a new version with this fix applied? 😊

**Comment by ofalvai** [comment]
Hello everyone!

Apologies for not noticing this earlier, my GitHub notifications were messed up and I missed all the issue and PR activity in this repo.

I issued a hotfix as version 0.7.1, you can update the custom component in HACS.
