### ISSUE TITLE
Remaining minutes issue

### ISSUE THREAD

**Issue by SwannyBFC** [ofalvai/home-assistant-candy#252]
Anyone know why my sensor.wash_cycle_remaining_time only displays the value 1 or 2 ?  But on my  washer it shows like this 

![PXL_20230129_091117747 MP](https://user-images.githubusercontent.com/12095329/215316931-ff8930d9-a5c8-4e22-b4f6-6e8177f46492.jpg)

**Comment by pyzimmer** [comment]
Hello, #51

**Comment by SwannyBFC** [comment]
Anyone know how to create this template sensor please ?

**Comment by gee-jay-bee** [comment]
Agreed. I had to remove the /60 on candy/client/model.py:66 to make my washing machine report the correct time:

```
            remaining_minutes=int(json["RemTime"]),
```

The value returned above really has precision of minutes so 1 hour 40 is reported as 100 minutes.

I think a template sensor might help if the washing machine is reporting remaining time as hours but we lose precision with the current implementation where machines really report minutes.

**Comment by glebsterx** [comment]
Hello!
I have the same problem and the same solution -- remove `/ 60` in the code of the model.py file

I already wanted to create an issue, but I saw that this one already exists =)
I could make a pull request, but I believe that the author had reasons to do exactly as it is done now and if he told us it would be cool =)

**Comment by SwannyBFC** [comment]
> Agreed. I had to remove the /60 on candy/client/model.py:66 to make my washing machine report the correct time:
> 
> ```
>             remaining_minutes=int(json["RemTime"]),
> ```
> 
> The value returned above really has precision of minutes so 1 hour 40 is reported as 100 minutes.
> 
> I think a template sensor might help if the washing machine is reporting remaining time as hours but we lose precision with the current implementation where machines really report minutes.

This fixed it for me ! Thanks
