### ISSUE TITLE
Support for NFC conectivity?

### ISSUE THREAD

**Issue by kyvaith** [ofalvai/home-assistant-candy#269]
My washer has a NFC spot not a WiFi connection. I can use na Candy app on my phone to select or create program and run washing process. Also I'm able to get washing statistics from the device. It could be possible to install a permanent NFC Reader and connect it to the HA server. Do you have any plans for that kind integration? Thanks.

**Comment by ofalvai** [comment]
Interesting, I've never heard of this NFC communication. Since this communication is probably completely different from the HTTP API this integration is using, it would make sense to create a completely new integration from scratch.
