### ISSUE TITLE
No entity after setup

### ISSUE THREAD

**Issue by Jacox98** [ofalvai/home-assistant-candy#3]
Hello,

first of all thank you so much for creating this home assistant integration.

I was able to get the key through the tool and finished the setup in ha, but in the end no entity is added, as in the picture.

![image](https://user-images.githubusercontent.com/35966887/131222836-df9d0b56-7afb-4913-b4fd-324258af7eca.png)

I can still read the data via the CLI

"statusWashing machine": {
                "WiFiStatus": "1",
                "Err": "0",
                "MachMd": "1",
                "Pr": "1",
                "PrPh": "0",
                "PrCode": "136",
                "SLevel": "0",
                "Temp": "40",
                "SpinSp": "8",
                "Opt1": "0",
                "Opt2": "0",
                "Opt3": "0",
                "Opt4": "0",
                "Opt5": "0",
                "Opt6": "0",
                "Opt7": "0",
                "Opt8": "0",
                "Opt9": "0",
                "Steam": "0",
                "DryT": "1",
                "DelVal": "0",
                "RemTime": "12540",
                "RecipeId": "0",
                "Lang": "0",
                "FillR": "0",
                "DisTestOn": "0",
                "DisTestRes": "0",
                "CheckUpState": "0",
                "T0W": "0",
                "TIW": "0",
                "T0R": "0",
                "numF": "0",
                "unbF": "0",
                "unbC": "0",
                "NtcW": "381",
                "NtcD": "631",
                "motS": "0",
                "APSoff": "0",
                "APSfreq": "61881",
                "chartL": "0"
        }

The washer dryer model is the following ROW4964DWMSE / 1-S

Thanks

**Comment by ofalvai** [comment]
Do you have sensors such as "Washing machine", "Wash cycle status" and "Wash cycle remaining time?" If you see these sensors then the integration is working. I'll look into why the integration page doesn't display the entities, this can be absolutely confusing.

**Comment by alancoleman1972** [comment]
Hi
For reference, my integration shows the same though I do have the relevlant entities...
![image](https://user-images.githubusercontent.com/57535336/131553418-fb708de4-5c4d-490b-ab41-4486e9eff83d.png)
![image](https://user-images.githubusercontent.com/57535336/131553523-2d7bf5e1-47f4-4b89-8bf3-5668c0d1f9b5.png)

**Comment by Jacox98** [comment]
Hi, the sensors work as expected, only the entity is missing for the rest great work
