### ISSUE TITLE
Possibility to not creating area

### ISSUE THREAD

**Issue by antoweb** [ofalvai/home-assistant-candy#30]
Please add the option to not automatic create an area when starting HA

After removed area loke kitchen or bathroom (automatic created from integration), restarting HA cause a re-creation

**Comment by antoweb** [comment]
Any news?

**Comment by ofalvai** [comment]
If this behavior is by design, then I can't do anything unfortunately.

**Comment by antoweb** [comment]
Yes you can remove from code the the suggested area for example?

**Comment by ofalvai** [comment]
That would remove a useful feature for others, so I don't want to do that. I recommend working around the behavior, eg. creating a placeholder area and assigning the Candy appliance to that, this way you can avoid the suggested area popping up.

**Comment by antoweb** [comment]
Ok but the placeholer area xannot be removed from lovelace dashboard.
Ok no problem, can you tell me please wich part of code i can comment/remove from python to avoid this  behavior, so i can edot muself the code files.
Thanks

**Comment by ofalvai** [comment]
Sure, you can delete this line: https://github.com/ofalvai/home-assistant-candy/blob/main/custom_components/candy/sensor.py#L59
