### ISSUE TITLE
Error communicating with API: KeyError('Pr')

### ISSUE THREAD

**Issue by lemeshovich** [ofalvai/home-assistant-candy#38]
Hello, my washing machine is Candy CO4 1062D3/2-S and im trying to add your integration to my Home Assistant.
I got needed ip and found a key with CandySimplyFi-tool then i completed your config flow.
But after, error appear in the integrations section
![image](https://user-images.githubusercontent.com/17667824/142467207-2b65c631-6e5f-4a6e-86df-d409463a1865.png)
Am i doing something wrong or my model isnt supported?

**Comment by ofalvai** [comment]
@lemeshovich looks like your model has a different API response than all the others I tried to support already :)

Please use [this tool](https://github.com/MelvinGr/CandySimplyFi-tool) to get an API response from the device and paste it here.

**Comment by lemeshovich** [comment]
i was already trying to do this, i have strange output trying to get data
![2021-11-18 20-09-40](https://user-images.githubusercontent.com/17667824/142473265-18e4f0f6-e8e1-493e-9afc-720f244b52ca.jpg)

**Comment by ofalvai** [comment]
Maybe try `getStatistic` without any encryption key? The original error message `KeyError('Pr')` means that this integration was able to read the JSON response, but couldn't find the `Pr` field in the response.

**Comment by lemeshovich** [comment]
![2021-11-18 21-02-50](https://user-images.githubusercontent.com/17667824/142480204-44c62925-99fa-4837-a86f-98cf3cdc7aa0.png)

**Comment by lemeshovich** [comment]
i got something
![Снимок экрана от 2021-11-18 21-18-59](https://user-images.githubusercontent.com/17667824/142482945-aa4f8ca6-0a53-4be9-9bef-ee3e85b8497a.jpg)

```
{
 "statusLavatrice":
{"WiFiStatus":"0",
  "Err":"0",
  "MachMd":"1",
  "PrNm":"2",
  "PrCode":"65",
  "PrPh":"0",
  "SLevel":"3",
  "Temp":"40",
  "SpinSp":"10",
  "Opt1":"0",
  "Opt2":"0",
  "Opt3":"0",
  "Opt4":"0",
  "Opt5":"0",
  "Opt6":"0",
  "Opt7":"0",
  "Opt8":"0",
  "Opt9":"0",
  "DelVal":"0",
  "Steam":"0",
  "DryT":"0",
  "RemTime":"10140",
  "RecipeId":"NULL",
  "CheckUpState":"0",
  "Lang":"1",
  "FillR":"0",
  "Det":"0",
  "Soft":"0",
  "DetWarn":"0",
  "SoftWarn":"0",
  "DetPreW":"0",
  "SoftPreW":"0",
  "DPrgCnt":"0",
  "SPrgCnt":"0",
  "WaterHard":"0",
  "rED":"0"
 }
}
```

**Comment by lemeshovich** [comment]
There are 
  "PrNm":"2",
  "PrCode":"65",
  "PrPh":"0",
fields, but no "Pr"
any chances to fix this? @ofalvai

**Comment by ofalvai** [comment]
Sorry for the delay @lemeshovich, I also made this fix in #39, which will be released soon with other changes.

**Comment by lemeshovich** [comment]
TY for update! But i have another question, looking your code and my api responses i suppose that not only 3 device sensors should have appeared in HA.
![image](https://user-images.githubusercontent.com/17667824/143138085-8dfec38e-c3a9-4f9e-b3b2-4bae4d9e2f85.png)
For exemple it would be good to see Temp, SpinSp, FillR and Pr/PrNm with description as HA sensors.

**Comment by lemeshovich** [comment]
One more thing, i figured out that during washing value "DelVal" specifies more accurate remaining time in minutes. It is updating every each minute unlike seconds in "RemTime". And during washing machine is turned on but washing process is not running it looks like that "DelVal" specifies how many minutes before machine go to standby mode and start beeping.

**Comment by ofalvai** [comment]
> For exemple it would be good to see Temp, SpinSp, FillR and Pr/PrNm with description as HA sensors.

They are displayed as attributes for the main sensor. You can create a template sensor if you want to extract an attribute to its own sensor.

> One more thing, i figured out that during washing API value "DelVal" specifies more accurate remaining time in minutes. It is updating every each minute unlike seconds in "RemTime". And during washing machine is turned on but washing process is not running it looks like that "DelVal" specifies how many minutes before machine go to standby mode and start beeping (starting from 30).

That's interesting, `DelVal` in my model's response is almost always 0. I have a few API responses stored here for testing, and the delayed start state is the only occasion when `DelVal` is not zero: https://github.com/ofalvai/home-assistant-candy/blob/main/tests/fixtures/washing_machine/

Also, my device updates `RemTime` every minute, so it's another inconsistency across models...
