### ISSUE TITLE
Find the encryption key automatically

### ISSUE THREAD

**Issue by dzamlo** [ofalvai/home-assistant-candy#46]
This would avoid the need for the user to do the slightly complex process necessary by hand.

The script I posted on the forum should be robust enough if you handle the case where the key is full of zeros.

**Comment by ofalvai** [comment]
This is an excellent idea, can you send me the script link please?

**Comment by dzamlo** [comment]
https://www.online-python.com/pm93n5Sqg4

The only known case where this fails is when the key is full of zeroes ( `b"\x00"*16`) and this should be handled specialy.

**Comment by ofalvai** [comment]
@dzamlo I tried using this script with a few hex strings posted on the forums, but I couldn't get a single one decrypted, the script simply finished without printing a potential key. Is it something I'm doing wrong here?

![image](https://user-images.githubusercontent.com/1694986/143778427-e67e7772-dda3-4f73-8280-74d47cd153cb.png)

**Comment by dzamlo** [comment]
The example om the screenshot seems to be the one that fail because the user didn't copy the whole response.This won't happen in practice because we handle getting the answer.  So just ignore this example .

Does it fails with other example ?

And do you at least get the message with the number of potential key? If not this may due to the way you run the script: try to put the last line outside of the if.

**Comment by ofalvai** [comment]
Thank you for the help @dzamlo, I was indeed using an incorrect key.

I made lots of progress based on the Python snippet you posted, the integration can detect the encryption type now automatically: #52 

It's released as [0.7.0](https://github.com/ofalvai/home-assistant-candy/releases/tag/0.7.0), let me know if it works for you!
