### ISSUE TITLE
sensor.wash_cycle_remaining_time bad reporting

### ISSUE THREAD

**Issue by Archangel67** [ofalvai/home-assistant-candy#51]
hi, my washing machine model CBWMS914WH-S works fine, but there is only one problem the sensor.wash_cycle_remaining_time which marks in minutes while there are hours left.

**Comment by ofalvai** [comment]
Just to make sure I understand it correctly, does your sensor displays eg. 1 minute while the remaining time is 1 hour?

**Comment by Archangel67** [comment]
yes, sorry for my bad english.
yes it start at 2 min while the remaining time is 2 hour after 1h it change in 1min

**Comment by Archangel67** [comment]
@ofalvai any news? Thanks

**Comment by ofalvai** [comment]
I can't find a way unfortunately to automatically detect the unit of measurement. I am hoping that the majority of devices use minutes and only a few devices report the number in hours. I think the best workaround is to create a [template sensor](https://www.home-assistant.io/integrations/template/) that uses the same numeric value but defines a different unit of measurement.

**Comment by glebsterx** [comment]
@ofalvai It seems to me that the author of the issue had the same problem as I have - the washing machine gives the time in minutes, and the integration divides the minutes by 60 and gives the number of hours, setting the units to "minutes" in the attribute "remaining minutes"
I did PR #278 removing this division by 60
Have a look, please
