### ISSUE TITLE
Washing Machine & Tumble Dryer Setup Error

### ISSUE THREAD

**Issue by tempus2016** [ofalvai/home-assistant-candy#55]
I get an error when trying to input the IP's.  I'm in the UK if that makes any difference.  Found the IP's through my router settings.

This error originated from a custom integration.

`Logger: custom_components.candy.config_flow
Source: custom_components/candy/client/__init__.py:69
Integration: Candy (documentation, issues)
First occurred: 21:08:58 (8 occurrences)
Last logged: 21:17:43

Cannot connect to host 192.168.1.115:80 ssl:default [Connect call failed ('192.168.1.115', 80)]
Cannot connect to host 192.168.1.75:80 ssl:default [Connect call failed ('192.168.1.75', 80)]
Cannot connect to host 192.168.1.240:80 ssl:default [Connect call failed ('192.168.1.240', 80)]
Cannot connect to host 192.168.1.208:80 ssl:default [Connect call failed ('192.168.1.208', 80)]
Cannot connect to host 192.168.1.175:80 ssl:default [Connect call failed ('192.168.1.175', 80)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.175', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/candy/config_flow.py", line 45, in async_step_user
    encryption_type, key = await detect_encryption(
  File "/config/custom_components/candy/client/__init__.py", line 69, in detect_encryption
    async with session.get(url) as resp:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.175:80 ssl:default [Connect call failed ('192.168.1.175', 80)]`

**Comment by ofalvai** [comment]
It seems like the connection to the given IP is refused. Do you get a response with a different tool, for example with https://github.com/MelvinGr/CandySimplyFi-tool?

**Comment by vergalabs** [comment]
it also gives me the same error, as you suggested I tried to download the melvingr tool but if I open the file.exe in Windows it gives me an error.  I read that it is also possible to open it in home assistant but I don't understand how to do it I'm a newbie in home assistant

**Comment by tempus2016** [comment]
> It seems like the connection to the given IP is refused. Do you get a response with a different tool, for example with https://github.com/MelvinGr/CandySimplyFi-tool?

I get this error when using that tool:
`CandySimplyFi.cpp:38:11: warning: result of comparison of constant 255 with
      expression of type 'const char' is always true
      [-Wtautological-constant-out-of-range-compare]
                        if (ch != ignore_code && ch != '\r' && ch != '\n...
                            ~~ ^  ~~~~~~~~~~~
CandySimplyFi.cpp:60:28: warning: result of comparison of constant 255 with
      expression of type 'const std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >::value_type'
      (aka 'const char') is always false
      [-Wtautological-constant-out-of-range-compare]
                                if (known_plaintext[j] == ignore_code)
                                    ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~
CandySimplyFi.cpp:79:52: warning: result of comparison of constant 255 with
      expression of type 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >::value_type'
      (aka 'char') is always false
      [-Wtautological-constant-out-of-range-compare]
  ...if (expanded_key[x % expanded_key.length()] == ignore_code)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~
CandySimplyFi.cpp:186:17: warning: '&&' within '||' [-Wlogical-op-parentheses]
        if ((argc == 3 && strcmp(argv[2], "getkey") != 0 || argc < 3) &...
             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~
CandySimplyFi.cpp:186:17: note: place parentheses around the '&&' expression to
      silence this warning
        if ((argc == 3 && strcmp(argv[2], "getkey") != 0 || argc < 3) &...
                       ^
             (                                          )
4 warnings generated.`

**Comment by ofalvai** [comment]
I can't help with this issue unfortunately, you might get help on the tool's issue tracker.
