### ISSUE TITLE
Not all sensors available in HA for Tumble Dryer

### ISSUE THREAD

**Issue by astraliens** [ofalvai/home-assistant-candy#62]
Hello, I've got issue with sensors, with tumble dryer. I'm having only 3 entities in HA: "Dryer cycle remaining time", "Dryer cycle status", "Tumble dryer". 
But in json data from device I can see all listed in your code params, it seems that in my situation HA can't see all sensors. There are missing "DoorState", "WaterTankFull", "CleanFilter" and some other items.

Here is data from device:

```
{
        "statusTD":
{"StatoWiFi":"0",
                "StatoTD":"2",
                "CodiceErrore":"0",
                "Pr":"5",
                "PrPh":"2",
                "RemTime":"76",
                "DryLev":"4",
                "Time":"0",
                "Rapido":"0",
                "Opt1":"1",
                "Opt2":"1",
                "Opt3":"0",
                "Opt4":"0",
                "Opt5":"0",
                "Opt6":"0",
                "Opt7":"0",
                "Opt8":"0",
                "Refresh":"0",
                "CleanFilter":"0",
                "WaterTankFull":"0",
                "DryingManagerLevel":"1",
                "DelVal":"0",
                "DoorState":"1",
                "RecipeId":"NULL",
                "CheckUpState":"0"
        }
}
```

**Comment by ofalvai** [comment]
This integration is not supposed to expose every JSON field as a sensor, but it tries to parse the most meaningful ones. You are right that there are 3 sensors, but some other fields are exposed as attributes of the main sensor. You can create a template sensor from an attribute if needed.

**Comment by astraliens** [comment]
My fault, did not found that most of params are attributes.
But maybe it'll be better to move "DoorState", "WaterTankFull", "CleanFilter" to regular sensor, coz they are "sensors" in meanfull
